// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzsbixyxpzinnpegpnfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6c2JpeHl4cHppbm5wZWdwbmZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYwMjA3NTgsImV4cCI6MjA4MTU5Njc1OH0.w-hdYB3sPLpThVXwuXAe-aM3yr4kQnYjxOT1JQM3qSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});